"""add posted_at to jobs

Revision ID: 6221887b9442
Revises: 566064a4a764
Create Date: 2026-07-26 20:46:02.821233
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6221887b9442"
down_revision: str | None = "566064a4a764"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_jobs_posted_at"), "jobs", ["posted_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_posted_at"), table_name="jobs")
    op.drop_column("jobs", "posted_at")
    # ### end Alembic commands ###
