"""add location_kind to jobs

Revision ID: da85c423b35e
Revises: bd4cba33f122
Create Date: 2026-07-28 18:24:15.138703
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "da85c423b35e"
down_revision: str | None = "bd4cba33f122"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows need a legal value before the CHECK lands; the next discovery
    # run reclassifies them properly.
    op.add_column(
        "jobs",
        sa.Column(
            "location_kind",
            sa.String(length=16),
            nullable=False,
            server_default="unknown",
        ),
    )
    op.alter_column("jobs", "location_kind", server_default=None)
    op.create_index(op.f("ix_jobs_location_kind"), "jobs", ["location_kind"], unique=False)
    op.create_check_constraint(
        "ck_jobs_location_kind",
        "jobs",
        "location_kind IN ('india', 'remote', 'overseas', 'unknown')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jobs_location_kind"), table_name="jobs")
    op.drop_column("jobs", "location_kind")
    # ### end Alembic commands ###
