"""widen external ids for long provider slugs

Revision ID: ee93538ff3a3
Revises: da85c423b35e
Create Date: 2026-07-30 15:12:11.253748
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ee93538ff3a3"
down_revision: str | None = "da85c423b35e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs",
        "external_id",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "jobs",
        "ats_job_id",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=512),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "jobs",
        "ats_job_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=128),
        existing_nullable=True,
    )
    op.alter_column(
        "jobs",
        "external_id",
        existing_type=sa.String(length=512),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
