"""A static lexicon of technology tokens, for the `unlisted_token` prose scan.

Deliberately a checked-in list rather than NER. NER needs a model, is
nondeterministic, and cannot be unit-tested against a fixed expectation; a static
lexicon is auditable and its failure mode is a false negative — which the
`unknown_skill` rule already covers for anything the model explicitly declares.

Extend freely: a token added here can only ever produce more scrutiny, never less.
"""

from .normalize import normalize_skill

_RAW_LEXICON: tuple[str, ...] = (
    # Languages
    "Python",
    "JavaScript",
    "TypeScript",
    "Java",
    "Kotlin",
    "Swift",
    "Go",
    "Golang",
    "Rust",
    "C",
    "C++",
    "C#",
    "Ruby",
    "PHP",
    "Scala",
    "Perl",
    "Haskell",
    "Elixir",
    "Erlang",
    "Clojure",
    "Lua",
    "Dart",
    "R",
    "MATLAB",
    "Objective-C",
    "Groovy",
    "Solidity",
    "Zig",
    "OCaml",
    "F#",
    "Julia",
    "COBOL",
    "Fortran",
    "Assembly",
    "Bash",
    "Shell",
    "PowerShell",
    "SQL",
    "PLSQL",
    "TSQL",
    "HTML",
    "CSS",
    "SASS",
    "SCSS",
    "Less",
    "GraphQL",
    "WebAssembly",
    # Frontend
    "React",
    "ReactJS",
    "Next.js",
    "Vue",
    "Vue.js",
    "Nuxt",
    "Angular",
    "AngularJS",
    "Svelte",
    "SvelteKit",
    "Ember",
    "Backbone",
    "jQuery",
    "Redux",
    "MobX",
    "Zustand",
    "Recoil",
    "Tailwind",
    "TailwindCSS",
    "Bootstrap",
    "Material-UI",
    "MUI",
    "Chakra",
    "Ant Design",
    "Styled Components",
    "Emotion",
    "Webpack",
    "Vite",
    "Rollup",
    "Parcel",
    "Babel",
    "ESLint",
    "Prettier",
    "Storybook",
    "React Native",
    "Flutter",
    "Ionic",
    "Electron",
    "Three.js",
    "D3",
    "D3.js",
    "Chart.js",
    "Recharts",
    # Backend / frameworks
    "Node.js",
    "NodeJS",
    "Express",
    "Express.js",
    "Nest.js",
    "NestJS",
    "Fastify",
    "Koa",
    "Hapi",
    "Django",
    "Flask",
    "FastAPI",
    "Pyramid",
    "Tornado",
    "Celery",
    "Rails",
    "Ruby on Rails",
    "Sinatra",
    "Laravel",
    "Symfony",
    "Spring",
    "Spring Boot",
    "Hibernate",
    "Micronaut",
    "Quarkus",
    "Vert.x",
    "Play",
    "Gin",
    "Echo",
    "Fiber",
    "Actix",
    "Rocket",
    "Axum",
    "Phoenix",
    "ASP.NET",
    ".NET",
    "Blazor",
    # Databases
    "PostgreSQL",
    "Postgres",
    "MySQL",
    "MariaDB",
    "SQLite",
    "Oracle",
    "SQL Server",
    "MongoDB",
    "Cassandra",
    "CouchDB",
    "DynamoDB",
    "Redis",
    "Memcached",
    "Neo4j",
    "Elasticsearch",
    "OpenSearch",
    "Solr",
    "ClickHouse",
    "Snowflake",
    "BigQuery",
    "Redshift",
    "Databricks",
    "InfluxDB",
    "TimescaleDB",
    "CockroachDB",
    "Firestore",
    "Firebase",
    "Supabase",
    "PlanetScale",
    "pgvector",
    "Pinecone",
    "Weaviate",
    "Qdrant",
    "Milvus",
    "Chroma",
    # Infra / cloud / devops
    "AWS",
    "Azure",
    "GCP",
    "Google Cloud",
    "Heroku",
    "Vercel",
    "Netlify",
    "DigitalOcean",
    "Linode",
    "Cloudflare",
    "Docker",
    "Kubernetes",
    "K8s",
    "Helm",
    "OpenShift",
    "Terraform",
    "Pulumi",
    "Ansible",
    "Chef",
    "Puppet",
    "Vagrant",
    "Jenkins",
    "CircleCI",
    "TravisCI",
    "GitHub Actions",
    "GitLab CI",
    "ArgoCD",
    "Spinnaker",
    "Nginx",
    "Apache",
    "HAProxy",
    "Envoy",
    "Istio",
    "Consul",
    "Vault",
    "Prometheus",
    "Grafana",
    "Datadog",
    "New Relic",
    "Sentry",
    "Splunk",
    "Kibana",
    "Logstash",
    "OpenTelemetry",
    "Jaeger",
    "PagerDuty",
    "Lambda",
    "EC2",
    "S3",
    "ECS",
    "EKS",
    "RDS",
    "CloudFront",
    "Route53",
    "CloudFormation",
    "SQS",
    "SNS",
    "EventBridge",
    "Step Functions",
    "Fargate",
    # Messaging / streaming / data
    "Kafka",
    "RabbitMQ",
    "ActiveMQ",
    "NATS",
    "Pulsar",
    "ZeroMQ",
    "Airflow",
    "Dagster",
    "Prefect",
    "dbt",
    "Spark",
    "Hadoop",
    "Flink",
    "Beam",
    "Hive",
    "Presto",
    "Trino",
    "Pandas",
    "NumPy",
    "SciPy",
    "Polars",
    "Dask",
    # ML / AI
    "TensorFlow",
    "PyTorch",
    "Keras",
    "scikit-learn",
    "sklearn",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "Hugging Face",
    "Transformers",
    "LangChain",
    "LlamaIndex",
    "OpenCV",
    "spaCy",
    "NLTK",
    "MLflow",
    "Kubeflow",
    "SageMaker",
    "Ray",
    # API / protocols / auth
    "REST",
    "RESTful",
    "gRPC",
    "SOAP",
    "WebSocket",
    "WebSockets",
    "WebRTC",
    "MQTT",
    "OAuth",
    "OAuth2",
    "OIDC",
    "SAML",
    "JWT",
    "OpenAPI",
    "Swagger",
    "Protobuf",
    "Avro",
    "Thrift",
    "tRPC",
    # Tooling / practice
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "SVN",
    "Mercurial",
    "Jira",
    "Confluence",
    "Linear",
    "Asana",
    "Trello",
    "Figma",
    "Postman",
    "Insomnia",
    "Selenium",
    "Cypress",
    "Playwright",
    "Puppeteer",
    "Jest",
    "Mocha",
    "Chai",
    "Vitest",
    "Pytest",
    "unittest",
    "JUnit",
    "TestNG",
    "RSpec",
    "Cucumber",
    "Locust",
    "JMeter",
    "Gradle",
    "Maven",
    "npm",
    "pnpm",
    "Yarn",
    "pip",
    "Poetry",
    "uv",
    "Cargo",
    "Bazel",
    "Make",
    "CMake",
    # Platforms / OS
    "Linux",
    "Ubuntu",
    "Debian",
    "CentOS",
    "RHEL",
    "Alpine",
    "macOS",
    "Windows",
    "iOS",
    "Android",
    "Unix",
    "FreeBSD",
    # Methodology
    "Agile",
    "Scrum",
    "Kanban",
    "CI/CD",
    "TDD",
    "BDD",
    "DDD",
    "Microservices",
    "Serverless",
    "GraphQL Federation",
    "Event Sourcing",
    "CQRS",
    "gitops",
)

#: Normalised lookup set. Used by the prose scan.
TECHNOLOGY_LEXICON: frozenset[str] = frozenset(
    normalize_skill(token) for token in _RAW_LEXICON if normalize_skill(token)
)

#: Longest number of whitespace-separated words in any lexicon entry ("Ruby on Rails").
MAX_LEXICON_NGRAM = 3


def is_technology(token: str) -> bool:
    return normalize_skill(token) in TECHNOLOGY_LEXICON
